export type ValidationLevel = "warn" | "strict" | "off";

export type ValidationConfig =
  | ValidationLevel
  | { [groupName: string]: ValidationLevel };

/**
 * Options for catalog management (plugin-specific features)
 */
export interface CatalogsOptions {
  /**
   * The default alias group to be used when no group is specified when adding a dependency
   * - if list of alias groups, it will be used in order
   * - if 'max', the most frequently used alias group will be used
   */
  default?: string[] | "max";
  /**
   * List of workspaces to ignore
   */
  ignoredWorkspaces?: string[];
  /**
   * Validation level for catalog usage
   * - 'warn': Show warnings when catalog versions are not used (default)
   * - 'strict': Throw errors when catalog versions are not used
   * - 'off': Disable validation
   * Can also be an object with group-specific settings
   */
  validation?: ValidationConfig;
}

/**
 * catalogs.yml file structure
 */
export interface CatalogsYml {
  options?: CatalogsOptions;
  list: {
    [alias: string]: {
      [packageName: string]: string;
    };
  };
}

/**
 * Internal configuration structure
 * Options are read from catalogs.yml
 * Catalogs are read from .yarnrc.yml (generated by 'yarn catalogs apply')
 */
export interface CatalogsConfiguration {
  options?: CatalogsOptions;

  /** Catalog groups from Yarn's native catalog/catalogs configuration in .yarnrc.yml */
  catalogs?: {
    [alias: string]: {
      [packageName: string]: string;
    };
  };
}
